spring:
  profiles:
    include:
      - nacos-dev
  datasource:
    username: root
    password: momincong
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teamsystem_cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    jdbc-url: jdbc:mysql://localhost:3306/teamsystem_cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

logging:
  level:
    org:
      springframework:
        security: DEBUG
